version: '3'
services:
  web:
    build:
      context: .
      args:
        NODE_ENV: development
        CONTAINER_IMAGE: node:20.2.0-slim
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: 'npm run dev'
    labels:
      traefik.enable: true
      traefik.http.routers.demo.rule: Host(`demo.localhost`)
    networks:
      workbench_microservice_clients:
        aliases:
          - demo.localhost
networks:
  workbench_microservice_clients:
    name: workbench_microservice
    external: true
